### ISSUE TITLE
So many warnings when trying to install on Windows 10 !?!

### ISSUE THREAD

**Issue by nodecentral** [PhilipMur/Serial-Comm-Tester#5]
Hi

I've downloaded the zip file and was really looking to give it a go. 

Byt when i tried to install it on Windows 10, it really doesn't like it
I have hit at least 3 warning messages so far, unknown zip files, Publisher cannot be verified etc.

Should I be concerned ?

**Comment by PhilipMur** [comment]
Hello Nodecentral,

The warning are generic warnings from windows and if you have any doubt don't install it by all means but the zip file was created by me and its on a google drive owned by me that's all the guarantee i can give you.

As for the publisher cannot be verified that's a warning to say the signed file is not hosted publicly and since that costs money im not doing that the code and exe are as is.

Always scan a file for viruses and if in doubt upload it to virus total a free website to scan files for viruses.

Best practices is to use the code yourself in Visual studio and compile the code to make your own executable file.

Its the only way to be 100% in control of what you are running on your system.

Philip
